##
## EPITECH PROJECT, 2023
## B-OOP-400-MPL-4-1-arcade-hugo.eschlimann
## File description:
## Makefile
##

all:
	make -C snake/ arcade_snake.so
	make -C nibbler/ arcade_nibbler.so

clean:
	make -C snake/ clean
	make -C nibbler/ clean

fclean: clean
	make -C snake/ fclean
	make -C nibbler/ fclean

re: fclean all